version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: mydb
    depends_on:
      - db
    volumes:
      - .:/home/nodejs/app
      - /home/nodejs/app/node_modules
    command: npm run dev

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

